CREATE DATABASE `vcl` /*!40100 DEFAULT CHARACTER SET latin1 */;

CREATE TABLE `LIST` (
  `LIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LIST_NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`LIST_ID`),
  UNIQUE KEY `LIST_ID_UNIQUE` (`LIST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=235 DEFAULT CHARSET=latin1;

CREATE TABLE `LIST_USER_JCT` (
  `LIST_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  PRIMARY KEY (`LIST_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LISTITEM` (
  `LISTITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LIST_ID` int(11) NOT NULL,
  `LISTITEM_DESC` varchar(45) NOT NULL,
  PRIMARY KEY (`LISTITEM_ID`),
  UNIQUE KEY `LISTITEM_ID_UNIQUE` (`LISTITEM_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

CREATE TABLE `LISTITEM_USER_JCT` (
  `LISTITEM_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `LISTITEM_DONE` tinyint(1) NOT NULL DEFAULT '0',
  `LISTITEM_DTE` datetime NOT NULL,
  PRIMARY KEY (`LISTITEM_DTE`,`USER_ID`,`LISTITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `USER` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_GRP` int(11) NOT NULL,
  `USER_NAME` varchar(45) NOT NULL,
  `USER_UN` varchar(45) NOT NULL,
  `USER_PW` varchar(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_ID_UNIQUE` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;
